# Spring Configuration, ensure hibernate does not auto-create DB's prefer flyway to do it.
###
#   Database Settings
###
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/nyc5?useSSL=false
    username: golden
    password: password
    driverClassName: com.mysql.jdbc.Driver
    
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true    
        
logging:
  level:
    com.netflix: INFO
    org.springframework.web: INFO
        